services:
  ride-service:
    build: .
    image: rides-service-image
    container_name: rides-service
    restart: always
    ports:
      - "4030:4003"
    env_file:
      - .env
    networks:
      - users-kafka-net

networks:
  users-kafka-net:
    external: true